//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET_Phones2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> PhonesId { get; set; }
        public string UserName { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
    
        public virtual Phone Phone { get; set; }
    }
}
